### ISSUE TITLE
[BE] fix: 닉네임 검증 api CORS문제 해결 

### ISSUE THREAD

**Issue by soominsohn** [woowacourse-teams/2022-ternoko#132]
### As-is
닉네임 검증로직 api `/api/login/check` 실행 시 CORS 문제가 발생한다.
해당 URI를 Interceptor에 추가하지 않아서 생기는 문제이다.

### To-be
- [x] Interceptor 설정 경로를 수정한다.

**Comment by dongho108** [comment]
api를 잘못 호출하고 있었습니다!
원래 : `/api/login/check`
요청하던 url : `/api/login`
