### ISSUE TITLE
[BE] feat: Member role 검증 로직 추가

### ISSUE THREAD

**Issue by her0807** [woowacourse-teams/2022-ternoko#167]
### As-is
현재 코치 페이지와 크루 페이지가 나눠져 있고, `Role` 마다 할 수 있는 작업이 다르다. 
하지만 검증이 되지 않고 있다. 

### To-be
- [ ] payload 에 `Member role` 추가 
- [ ] `@CoachOnly` 커스텀 어노테이션 추가
- [ ] `@CrewOnly ` 커스텀 어노테이션 추가 
- [ ]  controller에 검증 로직 추가

**Comment by soominsohn** [comment]
`코치 본인이 코치 본인에게 면담 신청할 수 없게 수정`의 뜻이 무엇인지 알 수 있을까요?
저는 위 문장을 다음과 같이 이해했어요.
- 코치는 면담 예약이 가능하다. 그러한 경우 본인에게 면담 신청할 수 없게 수정한다.

그러나 현재 코치의 면담 예약기능은 존재하지 않기 때문에 해당 예외는 코치의 면담 예약기능이 추가 된다면 넣어야 할 기능이라고 생각합니다. 혹시 제가 문장을 잘못 이해한 것일까요? 😄 
이슈 생성하셔서 멘션합니당~~ @her0807

**Comment by her0807** [comment]
앗.. ! 지난번 데모데이 때 보니까 코치가 크루 페이지에 접근할 수 있게 된다면, 면담 신청도 가능하더라구요. 
그래서 갑자기 등록한 이슈 였는데, 앤지와 대화를 나누다 보니까 이건 `Role` 에 대한 검증이 필요할 것 같아요. 

`[BE] feat: 코치 본인이 코치 본인에게 면담 신청할 수 없게 수정` -> `[BE] feat: Member role 검증 로직 추가 로 변경해두겠습니다. `

**Comment by her0807** [comment]
## 터놓고 인증 인가의 흐름
해당 내용의 흐름은 아래와 같은 과정으로 이뤄졌습니다. 

- [ ] 현재 JWT Payload 가 member_id 만으로 이뤄졌는데, memberType 도 추가합니다.
- [ ] 추가 된 후에 `@onlyCrew` `@onlyCoach` CustomAnnotation 을 만듭니다!
- [ ] RequestScope 에 해당 요청을 보낸 사용자의 memberType 을 넣어줍니다.
- [ ] 그리고 Controller 의 요청이 닿을 때, RequestScope 에 존재하는 memberType 이 가능한 작업인지 확인합니다.
- [ ] 권한이 없는 작업이면 exception 을 날려주고, 권한이 있다면 작업을 수행합니다. 


새롭게 공부할 키워드는 `@Aspect` 와 `@RequestScope `

**Comment by her0807** [comment]
현재 코치와 크루 역할을 나누고 있는` Enum class name 이 memberType 인데, Role 로 변경하는건 어떨까요 ? `

member 필드로 가지고 있어서, member 라고 어미에 없어도 될 것 같고, 그러면 type 만 남는데 해당 역할에 대해서 구분하는 내용이라서
type 보다는 role 이 더 의미를 전달하기 좋을 것 같다고 생각되네요.

**Comment by her0807** [comment]
JWT 토큰에 `memberId` 외에도  `memberType` 을 추가하려고 보니까  claims 를 구성하는 요소가 여러개 있더라구요. 

그래서 알아보니, `claims` 는 단일 값이 아니라 `claim` 여러개가 모여서 구성되어 있어요. 

여기서    `subject` 값은  유니크 값이라서 claims  생성시 한개만 들어 갈 수 있고, 그외 나머지는 여러개 들어갈 수 있어요.
그래서 고유값인 memberId 에 대한 표시는 subject 로 해주고,  memberType 은 claim 을 추가하는 것으로 변경했습니다. 


```java

     return Jwts.builder()
                .setSubject(payload)
                .claim("memberType", "crew")
                .setIssuedAt(now)
                .setExpiration(validity)
                .signWith(key, SignatureAlgorithm.HS256)
                .compact();

```

**Comment by her0807** [comment]
## @DiscriminatorColumn 으로 member table 에 Role 만들어 주고 있는 부분

```java

@DiscriminatorColumn(name = "ROLE")
public class Member {
```
위 부분을 제거하고, 필드로 MemberType 가져가는 방식으로 변경하고 싶습니다. 

```java

    @Enumerated
    @Column(name = "ROLE")
    private MemberType m

```
이유는 payload 에 MemberType을  넣어주고 싶었어요. 그럴려면 createToken 하는 시점에 Id 뿐만 아니라 해당 타입의 MemberType 도 
반환 받아야 했으나, 현재는 상속 받은 구현체가 지정될 때 Role 이 생겨나기 때문에  구체 타입을 class Instance.of 하는 방식이 아니라면Member , Coach, Crew 어디에서도 MemberType을 확인 할 수가 없어요 !! 😭

따라서 필드로 가져가고 table column 명만 똑같이 Role 로 명시해주면 기존 로직이 깨지지 않고 진행이 가능하다는 것을 확인 했습니다. 

[@DiscriminatorColumn)](https://ict-nroo.tistory.com/128)

**Comment by her0807** [comment]
## 어노테이션의 라이프사이클
CoachOnly 와 CrewOnly 를 구현하기 위해서 CustomAnnotation 을 구현할 일이 생겼고, CustomAnnotation 을 구현하기 위해서
필수로  `Target, Retention` 이  설정으로 따라오고 있었습니다. 

- Target은 말 그대로 어노테이션을 사용할 때 어디에 사용할지 명시해두는 부분이었고, 저희는 memberType 을 검증할 예정이니 method 에 사용하면 될 것 같아서 `@Target(ElementType.METHOD)` 로 제한했습니다. 

- [Retention](https://jeong-pro.tistory.com/234)은 annotation의 life cycle  을 지정할 수 있는데 해당 annotation이 언제까지 유효할지 지정해두는 것입니다. 제가 생각하기에는 controller 에 요청이오면 해당 요청의 memberType 검증을 계속 해줘야하기 때문에 
 해당 어노테이션이 프로그램이 끝날 때까지 유지되어야한다고  생각되어 `@Retention(RetentionPolicy.RUNTIME)` 로 지정했습니다. 
```java

@Target(ElementType.METHOD)
@Retention(RetentionPolicy.RUNTIME)
public @interface CrewOnly {
}
```

**Comment by her0807** [comment]
controller 요청이 수행되기 전에 memberType 을 검증하기 위해서 `@Aspect` 를 사용했습니다. 

해당 어노테이션은 Spring AOP 을 하기 위해서 사용했습니다. 

controller 에 요청이 들어올 때마다 각 타입의 memberType 을 검증하는 로직이 추가되어야하는데, 

이는 사실 controller 의 관심사가 아니고, 중복되는 로직이기 때문에 관심사를 분리하고, 중복 로직을 제거하고자 했습니다. 
아래 클래스에서는 memberType 을 검증하는 로직이 있고, @Before 를 사용해서 Custom Annotation 인 @CrewOnly 가 붙을 경우 아래 로직을 수행할 수 있도록 하였습니다. 



```java

@Aspect
@Component
@RequiredArgsConstructor
public class LoginMemberVerifier {

    private final MemberTypeCache memberTypeCache;

    @Before("@annotation(com.woowacourse.ternoko.login.aop.CrewOnly)")
    public void checkMemberTyeCrew() {
        final MemberType memberType = memberTypeCache.getMemberType();
        if (!memberType.equals(MemberType.CREW)) {
            throw new CrewNotAllowedException(CREW_NOT_ALLOWED);
        }
    }

   }

```

**Comment by her0807** [comment]
## RequestScope 에 MemberType 넣기 

memberTypeCache 라는 RequestScope 에 MemberType 을 setting 하게되면 
response 가 가기 전까지 데이터가 살아있어요! 

그래서 controller 에서 요청이 온 시점에 어떤 memberType 의 요청인지 바로 알 수 있게 됩니다. 

해당 로직은 resolver 를 탄 모든 요청의 MemberType 을 RequestScope 에 넣어두는 로직이에요. 

```java
    @Override
    public Object resolveArgument(final MethodParameter parameter,
                                  final ModelAndViewContainer mavContainer,
                                  final NativeWebRequest webRequest,
                                  final WebDataBinderFactory binderFactory) {
        final String credentials = AuthorizationExtractor.extract(
                webRequest.getNativeRequest(HttpServletRequest.class));

        try {
            memberTypeCache.setMemberType(jwtProvider.getMemberType(credentials));
        } catch (NumberFormatException e) {
            throw new TokenNotValidException(UNAUTHORIZED_MEMBER);
        }

        jwtProvider.validateToken(credentials);
        return Long.valueOf(jwtProvider.extractSubject(credentials));
    }

```
