### ISSUE TITLE
[BE] : suggestion : interviewStatus 변경 로직 status Pattern 적용

### ISSUE THREAD

**Issue by her0807** [woowacourse-teams/2022-ternoko#243]
### As-is

현재는 Enum type 으로 status 가 관리되고 있는데, 상태가 많아짐에 따라 분기문도 늘어나고, 
변경 포인트가 의존성이 있는 클래스 전역에 퍼지는 문제를 발견했다. 
해당 내용을 상태패턴으로 풀어보면 어떨까 ?

### To-be

Enum Type -> Interface 로 변경 후 implements  한 상태 객체를 만들어서 상태 변경 책임을 각각 상태 객체에게 위임한다.

**Comment by dongho108** [comment]
상태변경 책임은 인터뷰에게 있고 각 상태별로 실행할 메서드를 상태에게 위임하는 것이 맞는 것 같아요

**Comment by HyeonbinSa** [comment]
저도 동의합니다. 다만 구현 방식에 있어서는 고민이 필요한 것 같아 이야기를 나눠봐야할 것 같습니다.
