### ISSUE TITLE
[BE] chore: local과 dev ddl을 create-drop으로 바꾼다.

### ISSUE THREAD

**Issue by dongho108** [woowacourse-teams/2022-ternoko#276]
### As-is
- 현재 ddl이 create라서 엔티티의 변화가 생길시 기존 테이블이 남아있어서 drop 후 create가 안된다.

### To-be
- ddl을 create-drop으로 바꾸면 어플리케이션이 내려가면서 기존 테이블이 drop되기 때문에 새로 create를 할때 테이블끼리 충돌이 발생하지 않는다.
- dev는 prod와 validate로 맞추기 전 시점까지만 create-drop을 유지한다.

**Comment by soominsohn** [comment]
동의합니다! create-drop으로 가야 버그가 생기는 경우가 줄어들 것 같습니다. 감사합니다 👍
