### ISSUE TITLE
[BE] refactor: 중복된 멤버 이름으로 닉네임 수정 시 반환 예외타입 변경

### ISSUE THREAD

**Issue by soominsohn** [woowacourse-teams/2022-ternoko#330]
### As-is
<img width="564" alt="image" src="https://user-images.githubusercontent.com/83059234/188565411-5ef14c71-d15d-4446-ba50-e47d87d254d0.png">
현재 500번대 에러를 터뜨리고 있습니다.

### To-be
- [ ] sql에러를 잡아서 변환해 400번대 에러를 반환하는 로직 작성

**Comment by her0807** [comment]
@soominsohn  해당 작업 진행되었나요 ?

**Comment by soominsohn** [comment]
수달이 assigned 하셨길래 이 작업도 하고 싶어하시는 줄 알았습니다~. 하실 의향 없으시면 다음주에 처리할게용~
