### ISSUE TITLE
[BE] refactor: 스프린트 1.5  내용을 refactoring 한다.

### ISSUE THREAD

**Issue by her0807** [woowacourse-teams/2022-ternoko#36]
### As-is
페어로 나뉘어 작성한 코드에 대해 리팩터링이 필요하다.

## business logic 🤔
- [x] controller return value 를 domain 에서 dto 로 일괄 변경
- [x] member → Coach/Crew 분류
- [x] 도메인 검증로직 추가
- [x] FormItemDto → FormItemReqeust, FormItemResponse로 분리
- [x] DTO 내의 final 제거 및 `@NoArgsConstructor` 추가하기
- [x] MemberService에 line23 공백 추가~~
- [x] request 검증 어노테이션 추가
- [ ] #50
```
@Column(nullable = false, length = 30)
private String crewNickname;
```
- [x] 전체적으로 회색 import문 제거 → intelliJ에서 설정해놔도 좋을 듯
- [x] formItem → ManyToOne 양방향 매핑으로
- [x] 연월 기준으로 조회해오는거 between vs where

## test logic 🤔
- [x]  test fixture 정리
- [x]  displayName 규칙 적용

**Comment by her0807** [comment]
domain entity 검증 추가는 도메인 요구사항에 따라서 달라지는 부분이라서 논의가 필요할 듯 !
`의견이 필요합니당`

**Comment by dongho108** [comment]
`MayToOne`이 아니라 `ManyToOne` 양방향 매핑이 필요해서 양방향 매핑으로 이슈 수정했어요!
