### ISSUE TITLE
[BE] feat: 운영서버에서 코치 입장 회원가입 시 coach 도메인 임시테이블 생성 문제

### ISSUE THREAD

**Issue by soominsohn** [woowacourse-teams/2022-ternoko#360]
### As-is
<img width="765" alt="image" src="https://user-images.githubusercontent.com/83059234/189823940-ec48d1e9-f34a-415e-b2f2-5c7215003a00.png">

저 HT_coach테이블을 찾지 못한다는 문제인데 HT 테이블은 상속관계 매핑시 jpa에서 임시로 생성되는 테이블 입니다.
그러나 저희 ddl-auto 설정이 validate으로 되어있어서 임시 테이블 생성에 문제가 생기는 것 같아요
관련 자료
https://in.relation.to/2017/02/01/non-temporary-table-bulk-id-strategies/
https://stackoverflow.com/questions/42763309/how-to-set-hibernate-bulk-id-strategy-in-spring-boot-application
설정추가

**Comment by dongho108** [comment]
임시테이블을 생성하지 않도록 `bulk_id_strategy: org.hibernate.hql.spi.id.inline.InlineIdsInClauseBulkIdStrategy` 설정을 추가해서 해결하였습니다~
