### ISSUE TITLE
[FE] feat: nginx에 캐시 적용

### ISSUE THREAD

**Issue by soominsohn** [woowacourse-teams/2022-ternoko#365]
### As-is
- 현재 정적파일들에 대해 nginx 캐시 적용이 필요합니다. 

### To-be
- [x] 프론트 정적파일에 대해 nginx에 캐시를 적용한다.

**Comment by lokba** [comment]
개발용 nginx에 캐시 적용하였습니다.
프로덕션은 9월 22일(목)에 진행하겠습니다.
