### ISSUE TITLE
[BE/FE] git: PR merge 방식 변경 제안

### ISSUE THREAD

**Issue by her0807** [woowacourse-teams/2022-ternoko#37]
### As-is
터놓고 기존 PR은 create merge commit 방식임.
이 방식은 모든 커밋이력이 남게되어 이력이 깔끔하지 않다. + 머지커밋도 추가됨

![스크린샷 2022-07-08 오전 9 55 58](https://user-images.githubusercontent.com/26570275/177895115-898c257b-5990-49e1-9f06-be7798ef54c7.png)

### To-be
PR 머지 방식을 Squash Merge 방식으로 변경하는 것을 제안합니다.

### Result
Squash Merge 방식을 택한다.

**Comment by lokba** [comment]
저도 `squash` 방식이 더 좋아보이네요 👍

**Comment by soominsohn** [comment]
`squash` 방식 채택으로 결정되었습니다.
