### ISSUE TITLE
[BE] feat: 데이터베이스에 인덱스 적용

### ISSUE THREAD

**Issue by soominsohn** [woowacourse-teams/2022-ternoko#370]
### As-is
현재 데이터베이스 칼럼에 인덱스 적용이 안되어있습니다. 

### To-be
- [ ] 인덱스를 적용 할 수 있는 테이블과 칼럼을 찾아본다.
- [ ] 인덱스를 적용한다.

**Comment by dongho108** [comment]
## 작업계획

1. 인덱스를 걸 테이블과 컬럼 설계
2. 더미데이터 생성
3. 적용
4. 성능측정

**Comment by dongho108** [comment]
운영 DB에는 인덱싱 안걸려있더라구요 ㅎ
