### ISSUE TITLE
[BE] feat: 코치 스케줄 생성시 기존에 예약된 면담 시간이 없을 경우 에러가 발생한다.

### ISSUE THREAD

**Issue by her0807** [woowacourse-teams/2022-ternoko#400]
### To-be
put 칠 경우 면담이 있으면 되는 시간을 삭제하지 않도록 한다 -> USED로 냅둔다.

**Comment by dongho108** [comment]
1. 코치의 가능한 시간을 수정할 때 기존의 시간이 있다면 해당 데이터는 삭제하지 않는다.
    - 예시) delete할 때 where status = OPEN 
2. interview가 생성될때 면담가능한시간 id를 가져야한다.
