### ISSUE TITLE
[BE] fix: 한달 단위로 되는 시간 표시  

### ISSUE THREAD

**Issue by her0807** [woowacourse-teams/2022-ternoko#416]
### As-is
브라운이 시간이 없는데 / 시간이 있다고 표시되는 문제발견 

<img width="1079" alt="스크린샷 2022-09-28 오전 10 20 21" src="https://user-images.githubusercontent.com/26570275/192665770-79229b5f-8767-4f3a-9854-75fb13295f3f.png">

**Comment by dongho108** [comment]
빠르네용
