### ISSUE TITLE
[BE] refactor: FE 이미지 용량 최적화 위해 Slack 이미지 사이즈 변경

### ISSUE THREAD

**Issue by HyeonbinSa** [woowacourse-teams/2022-ternoko#436]
### As-is
- `userInfoResponse.getUserImage192()`와 같이 192x192로 받아오고 있음.
### To-be
<img width="201" alt="image" src="https://user-images.githubusercontent.com/36189291/193563530-46af3623-0f90-42fd-afbc-816388bca664.png">
Slack에서 위와 같은 사이즈로 이미지를 제공함에 따라 FE와 상의 후 해당 코드 수정 필요

**Comment by lokba** [comment]
기존에 슬랙 이미지는 192x192 사이즈로 가져오고 있습니다. 
코치 도메인과 크루 도메인의 슬랙 이미지 사이즈를 조사한 결과, 기존대로 192x192 사이즈가 적절하다고 판단하였습니다. 
해당 이슈는 close하겠습니다.
