### ISSUE TITLE
[BE] feat: ssh 인증서를 갱신한다.

### ISSUE THREAD

**Issue by her0807** [woowacourse-teams/2022-ternoko#477]
#### 11월 1일까지 만료래요 ☺️
<img width="404" alt="스크린샷 2022-10-14 오후 4 01 14" src="https://user-images.githubusercontent.com/26570275/195809395-377eeb65-2060-4f0b-8f6f-0f26b1b42d4e.png">

**Comment by soominsohn** [comment]
갱신 완료
작업내역은 밑에서 확인하실 수 있습니다.
[SSL 인증서 갱신](https://necessary-sundial-178.notion.site/10-24-nginx-ssl-00530bd120d24730891f5adc40b42d6f)
