### ISSUE TITLE
[BE] refactor: 날짜 검증 로직 및 테스트 코드를 리팩토링한다.

### ISSUE THREAD

**Issue by dongho108** [woowacourse-teams/2022-ternoko#72]
### As-is
- 현재 날짜 검증 로직은 LocalDate.now()와 비교해 검증하고 있다.

### To-be
- 컨트롤러에서 서비스로 오늘날짜를 넣어주도록 수정한다.
- 테스트 코드시에 사용하는 픽스쳐를 리팩토링한다.

**Comment by Juhyung990122** [comment]
이거 Clock 먹여야하는거라 지금 해야하는건지 고민..
